# Generated by Django 3.1.4 on 2021-03-26 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_name', models.CharField(default='', max_length=50)),
                ('sender_name', models.CharField(default='', max_length=50)),
                ('receiver_name', models.CharField(default='', max_length=50)),
                ('product_name', models.CharField(default='', max_length=50)),
                ('product_weight', models.CharField(default='', max_length=50)),
                ('contact_number', models.CharField(default='', max_length=12)),
                ('pickup_address', models.TextField(default='', max_length=250)),
                ('delivery_address', models.TextField(default='', max_length=250)),
                ('delivery_city', models.TextField(default='', max_length=50)),
                ('DateTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery_Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=250)),
                ('phone_number', models.IntegerField()),
                ('aadhaar', models.CharField(max_length=12)),
                ('PAN_card', models.CharField(max_length=10)),
                ('Rc_no', models.CharField(max_length=16)),
                ('Driving_licence', models.CharField(max_length=16)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
