# Generated by Django 3.1.4 on 2021-03-24 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_person', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Receivepackage',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Sendackage',
        ),
    ]
