# Generated by Django 3.1.4 on 2021-03-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Completed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(default='', max_length=50)),
                ('receiver_name', models.CharField(default='', max_length=50)),
                ('product_name', models.CharField(default='', max_length=50)),
                ('product_weight', models.CharField(default='', max_length=50)),
                ('contact_number', models.CharField(default='', max_length=12)),
                ('pickup_address', models.TextField(default='', max_length=250)),
                ('delivery_address', models.TextField(default='', max_length=250)),
                ('delivery_city', models.TextField(default='', max_length=50)),
                ('DateTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ongoing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(default='', max_length=50)),
                ('receiver_name', models.CharField(default='', max_length=50)),
                ('product_name', models.CharField(default='', max_length=50)),
                ('product_weight', models.CharField(default='', max_length=50)),
                ('contact_number', models.CharField(default='', max_length=12)),
                ('pickup_address', models.TextField(default='', max_length=250)),
                ('delivery_address', models.TextField(default='', max_length=250)),
                ('delivery_city', models.TextField(default='', max_length=50)),
                ('DateTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rejected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(default='', max_length=50)),
                ('receiver_name', models.CharField(default='', max_length=50)),
                ('product_name', models.CharField(default='', max_length=50)),
                ('product_weight', models.CharField(default='', max_length=50)),
                ('contact_number', models.CharField(default='', max_length=12)),
                ('pickup_address', models.TextField(default='', max_length=250)),
                ('delivery_address', models.TextField(default='', max_length=250)),
                ('delivery_city', models.TextField(default='', max_length=50)),
                ('DateTime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
