# Generated by Django 3.1.4 on 2021-03-28 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery_person', '0002_completed_ongoing_rejected'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPersonProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone_Number', models.CharField(default='', max_length=12)),
                ('Address', models.TextField(max_length=250)),
                ('Aadhaar_Number', models.CharField(default='', max_length=12)),
                ('PAN_Number', models.CharField(default='', max_length=10)),
                ('Driving_licence_number', models.CharField(default='', max_length=16)),
                ('Vehicle_RC_number', models.CharField(default='', max_length=16)),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Delivery_Person',
        ),
    ]
