# Generated by Django 3.1.4 on 2021-03-24 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_person', '0002_auto_20210324_1643'),
        ('user', '0002_auto_20210324_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='requestpackage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.requestpackage'),
        ),
        migrations.AddField(
            model_name='order',
            name='sendackage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.sendpackage'),
        ),
    ]
