# Generated by Django 3.1.4 on 2021-03-22 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Receivepackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50)),
                ('sender_name', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=50)),
                ('product_weight', models.IntegerField(default='0')),
                ('Contact_number', models.IntegerField(default='0')),
                ('pickup_address', models.TextField(max_length=250)),
                ('delivery_address', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Sendpackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=50)),
                ('product_weight', models.IntegerField(default='0')),
                ('Contact_number', models.IntegerField(default='0')),
                ('pickup_address', models.TextField(max_length=250)),
                ('delivery_address', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone_Number', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
