# Generated by Django 3.1.4 on 2021-03-24 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_person', '0002_auto_20210324_1643'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requestpackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_name', models.CharField(default='', max_length=50)),
                ('sender_name', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=50)),
                ('product_weight', models.IntegerField(default='0')),
                ('Contact_number', models.IntegerField(default='0')),
                ('pickup_address', models.TextField(max_length=250)),
                ('delivery_address', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone_Number', models.IntegerField()),
                ('user', models.OneToOneField(default='2', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Receivepackage',
        ),
        migrations.AddField(
            model_name='sendpackage',
            name='sender_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='User_Profile',
        ),
    ]
